-- Idempotent creation and seeding of alert_types
CREATE TABLE IF NOT EXISTS alert_types (
  type_name text PRIMARY KEY,
  emoji text,
  payload jsonb,
  created_at timestamptz DEFAULT now()
);

-- Insert known event types from NWS (idempotent)
-- Emojis chosen heuristically based on keywords.

INSERT INTO alert_types (type_name, emoji, payload) VALUES
('911 Telephone Outage', '📞', jsonb_build_object('name','911 Telephone Outage')),
('Administrative Message', '📢', jsonb_build_object('name','Administrative Message')),
('Air Quality Alert', '😷', jsonb_build_object('name','Air Quality Alert')),
('Air Stagnation Advisory', '🌫️', jsonb_build_object('name','Air Stagnation Advisory')),
('Ashfall Advisory', '🌋', jsonb_build_object('name','Ashfall Advisory')),
('Ashfall Warning', '🌋', jsonb_build_object('name','Ashfall Warning')),
('Avalanche Advisory', '❄️', jsonb_build_object('name','Avalanche Advisory')),
('Avalanche Warning', '❄️', jsonb_build_object('name','Avalanche Warning')),
('Avalanche Watch', '❄️', jsonb_build_object('name','Avalanche Watch')),
('Beach Hazards Statement', '🏖️', jsonb_build_object('name','Beach Hazards Statement')),
('Blizzard Warning', '🌨️', jsonb_build_object('name','Blizzard Warning')),
('Blowing Dust Advisory', '🌫️', jsonb_build_object('name','Blowing Dust Advisory')),
('Blowing Dust Warning', '🌫️', jsonb_build_object('name','Blowing Dust Warning')),
('Blue Alert', '🔵', jsonb_build_object('name','Blue Alert')),
('Brisk Wind Advisory', '💨', jsonb_build_object('name','Brisk Wind Advisory')),
('Child Abduction Emergency', '🚨', jsonb_build_object('name','Child Abduction Emergency')),
('Civil Danger Warning', '🚨', jsonb_build_object('name','Civil Danger Warning')),
('Civil Emergency Message', '🚨', jsonb_build_object('name','Civil Emergency Message')),
('Coastal Flood Advisory', '🏖️', jsonb_build_object('name','Coastal Flood Advisory')),
('Coastal Flood Statement', '🏖️', jsonb_build_object('name','Coastal Flood Statement')),
('Coastal Flood Warning', '🏖️', jsonb_build_object('name','Coastal Flood Warning')),
('Coastal Flood Watch', '🏖️', jsonb_build_object('name','Coastal Flood Watch')),
('Cold Weather Advisory', '🧊', jsonb_build_object('name','Cold Weather Advisory')),
('Dense Fog Advisory', '🌫️', jsonb_build_object('name','Dense Fog Advisory')),
('Dense Smoke Advisory', '🌫️', jsonb_build_object('name','Dense Smoke Advisory')),
('Dust Advisory', '🌫️', jsonb_build_object('name','Dust Advisory')),
('Dust Storm Warning', '🌫️', jsonb_build_object('name','Dust Storm Warning')),
('Earthquake Warning', '🌎', jsonb_build_object('name','Earthquake Warning')),
('Evacuation Immediate', '🚨', jsonb_build_object('name','Evacuation Immediate')),
('Extreme Heat Warning', '🔥', jsonb_build_object('name','Extreme Heat Warning')),
('Extreme Heat Watch', '🔥', jsonb_build_object('name','Extreme Heat Watch')),
('Extreme Cold Warning', '🧊', jsonb_build_object('name','Extreme Cold Warning')),
('Extreme Cold Watch', '🧊', jsonb_build_object('name','Extreme Cold Watch')),
('Extreme Fire Danger', '🔥', jsonb_build_object('name','Extreme Fire Danger')),
('Extreme Wind Warning', '💨', jsonb_build_object('name','Extreme Wind Warning')),
('Fire Warning', '🔥', jsonb_build_object('name','Fire Warning')),
('Fire Weather Watch', '🔥', jsonb_build_object('name','Fire Weather Watch')),
('Flash Flood Statement', '🌊', jsonb_build_object('name','Flash Flood Statement')),
('Flash Flood Warning', '🌊', jsonb_build_object('name','Flash Flood Warning')),
('Flash Flood Watch', '🌊', jsonb_build_object('name','Flash Flood Watch')),
('Flood Advisory', '🌧️', jsonb_build_object('name','Flood Advisory')),
('Flood Statement', '🌧️', jsonb_build_object('name','Flood Statement')),
('Flood Warning', '🌧️', jsonb_build_object('name','Flood Warning')),
('Flood Watch', '🌧️', jsonb_build_object('name','Flood Watch')),
('Freeze Warning', '🧊', jsonb_build_object('name','Freeze Warning')),
('Freeze Watch', '🧊', jsonb_build_object('name','Freeze Watch')),
('Freezing Fog Advisory', '🌫️', jsonb_build_object('name','Freezing Fog Advisory')),
('Freezing Spray Advisory', '🧊', jsonb_build_object('name','Freezing Spray Advisory')),
('Frost Advisory', '🧊', jsonb_build_object('name','Frost Advisory')),
('Gale Warning', '⛵', jsonb_build_object('name','Gale Warning')),
('Gale Watch', '⛵', jsonb_build_object('name','Gale Watch')),
('Hazardous Materials Warning', '☣️', jsonb_build_object('name','Hazardous Materials Warning')),
('Hazardous Seas Warning', '🚢', jsonb_build_object('name','Hazardous Seas Warning')),
('Hazardous Seas Watch', '🚢', jsonb_build_object('name','Hazardous Seas Watch')),
('Hazardous Weather Outlook', '⚠️', jsonb_build_object('name','Hazardous Weather Outlook')),
('Heat Advisory', '🔥', jsonb_build_object('name','Heat Advisory')),
('High Surf Advisory', '🏄', jsonb_build_object('name','High Surf Advisory')),
('High Surf Warning', '🏄', jsonb_build_object('name','High Surf Warning')),
('High Wind Warning', '💨', jsonb_build_object('name','High Wind Warning')),
('High Wind Watch', '💨', jsonb_build_object('name','High Wind Watch')),
('Hurricane Force Wind Warning', '🌀', jsonb_build_object('name','Hurricane Force Wind Warning')),
('Hurricane Force Wind Watch', '🌀', jsonb_build_object('name','Hurricane Force Wind Watch')),
('Hurricane Warning', '🌀', jsonb_build_object('name','Hurricane Warning')),
('Hurricane Watch', '🌀', jsonb_build_object('name','Hurricane Watch')),
('Ice Storm Warning', '🧊', jsonb_build_object('name','Ice Storm Warning')),
('Lake Effect Snow Warning', '❄️', jsonb_build_object('name','Lake Effect Snow Warning')),
('Lake Wind Advisory', '💨', jsonb_build_object('name','Lake Wind Advisory')),
('Lakeshore Flood Advisory', '🏖️', jsonb_build_object('name','Lakeshore Flood Advisory')),
('Lakeshore Flood Statement', '🏖️', jsonb_build_object('name','Lakeshore Flood Statement')),
('Lakeshore Flood Warning', '🏖️', jsonb_build_object('name','Lakeshore Flood Warning')),
('Lakeshore Flood Watch', '🏖️', jsonb_build_object('name','Lakeshore Flood Watch')),
('Law Enforcement Warning', '🚔', jsonb_build_object('name','Law Enforcement Warning')),
('Local Area Emergency', '🚨', jsonb_build_object('name','Local Area Emergency')),
('Low Water Advisory', '💧', jsonb_build_object('name','Low Water Advisory')),
('Marine Weather Statement', '🚢', jsonb_build_object('name','Marine Weather Statement')),
('Nuclear Power Plant Warning', '☢️', jsonb_build_object('name','Nuclear Power Plant Warning')),
('Radiological Hazard Warning', '☢️', jsonb_build_object('name','Radiological Hazard Warning')),
('Red Flag Warning', '🔥', jsonb_build_object('name','Red Flag Warning')),
('Rip Current Statement', '🏖️', jsonb_build_object('name','Rip Current Statement')),
('Severe Thunderstorm Warning', '⛈️', jsonb_build_object('name','Severe Thunderstorm Warning')),
('Severe Thunderstorm Watch', '⛈️', jsonb_build_object('name','Severe Thunderstorm Watch')),
('Severe Weather Statement', '⚠️', jsonb_build_object('name','Severe Weather Statement')),
('Shelter In Place Warning', '🏠', jsonb_build_object('name','Shelter In Place Warning')),
('Short Term Forecast', '📡', jsonb_build_object('name','Short Term Forecast')),
('Small Craft Advisory', '⛵', jsonb_build_object('name','Small Craft Advisory')),
('Snow Squall Warning', '❄️', jsonb_build_object('name','Snow Squall Warning')),
('Special Marine Warning', '🚢', jsonb_build_object('name','Special Marine Warning')),
('Special Weather Statement', '⚠️', jsonb_build_object('name','Special Weather Statement')),
('Storm Surge Warning', '🌊', jsonb_build_object('name','Storm Surge Warning')),
('Storm Surge Watch', '🌊', jsonb_build_object('name','Storm Surge Watch')),
('Storm Warning', '⛈️', jsonb_build_object('name','Storm Warning')),
('Storm Watch', '⛈️', jsonb_build_object('name','Storm Watch')),
('Test', '🔁', jsonb_build_object('name','Test')),
('Tornado Warning', '🌪️', jsonb_build_object('name','Tornado Warning')),
('Tornado Watch', '🌪️', jsonb_build_object('name','Tornado Watch')),
('Tropical Cyclone Local Statement', '🌀', jsonb_build_object('name','Tropical Cyclone Local Statement')),
('Tropical Storm Warning', '🌀', jsonb_build_object('name','Tropical Storm Warning')),
('Tropical Storm Watch', '🌀', jsonb_build_object('name','Tropical Storm Watch')),
('Tsunami Advisory', '🌊', jsonb_build_object('name','Tsunami Advisory')),
('Tsunami Warning', '🌊', jsonb_build_object('name','Tsunami Warning')),
('Tsunami Watch', '🌊', jsonb_build_object('name','Tsunami Watch')),
('Typhoon Warning', '🌀', jsonb_build_object('name','Typhoon Warning')),
('Typhoon Watch', '🌀', jsonb_build_object('name','Typhoon Watch')),
('Volcano Warning', '🌋', jsonb_build_object('name','Volcano Warning')),
('Wind Advisory', '💨', jsonb_build_object('name','Wind Advisory')),
('Winter Storm Warning', '❄️', jsonb_build_object('name','Winter Storm Warning')),
('Winter Storm Watch', '❄️', jsonb_build_object('name','Winter Storm Watch')),
('Winter Weather Advisory', '❄️', jsonb_build_object('name','Winter Weather Advisory'))
ON CONFLICT (type_name) DO UPDATE SET emoji = COALESCE(alert_types.emoji, EXCLUDED.emoji), payload = COALESCE(alert_types.payload, EXCLUDED.payload);

-- End of seed file
